on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  auto-update:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cache
          path: "~/scoop"
      - name: Install Scoop
        continue-on-error: true
        run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          iwr -useb get.scoop.sh | iex
      - name: Version Check & Update
        env:
          SCOOP_HOME: "~/scoop/apps/scoop/current"
        run: ./bin/checkver.ps1 * -u
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'bucket'
          default_author: github_actions
          message: "Bucket updates"
          push: true
